### ISSUE TITLE
Error with cocos2d-x and iOS 7.1

### ISSUE THREAD

**Issue by hydex86** [hovergames/avalon#47]
I'm trying to integrate this library, but i got this error:

error: /Users/dani/Documents/cocos2d-x-2.2.2/extensions/avalon/avalon/physics/vendors/../../../vendors/b2dJson/c++: No such file or directory

I followed following steps:

- Cloned repo in this path (where is located cocos2d-x): /Users/dani/Documents/cocos2d-x-2.2.2/extensions/
- I added /Users/dani/Documents/cocos2d-x-2.2.2/extensions/avalon/avalon to the project, and removed everything under platform except iOS folder
- I added /Users/dani/Documents/cocos2d-x-2.2.2/extensions/ to Header search path

Did I miss something? Thanks in advance

**Comment by michaelcontento** [comment]
closed as this project is no longer maintained - sorry :disappointed:
