### ISSUE TITLE
avalon/utils/platform.h not found

### ISSUE THREAD

**Issue by jslim89** [hovergames/avalon#52]
I got this error on **avalon/utils/platform.h** this file.

![header not found](https://cloud.githubusercontent.com/assets/797182/4967238/1342dda4-6802-11e4-8775-43a4c084a2f4.png)

my **Header Search Paths** is 

![header-search-paths](https://cloud.githubusercontent.com/assets/797182/4967241/6accb720-6802-11e4-8d93-0d63b731e9bb.png)

But if I change `#include <avalon/utils/platform.h>` to `#include "platform.h"`, then it works

Anything wrong this this ?

**Comment by michaelcontento** [comment]
closed as this project is no longer maintained - sorry :disappointed:
